sparklemotion/sqlite3-ruby

Gemfile
tasks/gem.rake
tasks/native.rake
tasks/vendor_sqlite3.rake

[rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock) is the successor of the [rake-compiler-dev-box](https://github.com/tjschuck/rake-compiler-dev-box) - at least in my little universe :smile:
No really - it builds gems faster, with little to no setup and is easy to integrate. A simple 'rake gem:windows' usually does everything.
I tested 'rake gem:windows' on Ubuntu and Windows-7 successfully. I also tested the resulting gems on RubyInstaller versions 2.1.4-x64, 2.2.1-x86 and 2.2.1-x64 on Windows-7 with the test suite and got no failures. OS-X is currently untested.
This PR also updates the sqlite version, although this is not related to rake-compiler-dock.
<b>Update:</b>
I updated the Gemfile und the link to rake-compiler-dock, which has now moved to the …

Make use of rake-compiler-dock for building windows binary gems

---

ext/sqlite3/database.c
test/test_database.rb

Hello,
I was unable to return BLOB values from created functions using the gem. The change in this pull request allows returning of a BLOB value from a created function.
If the encoding on the string value is ASCII-8BIT, then the return value is a BLOB instead of TEXT. This is important if binary data contains null values, or is otherwise not valid UTF-8.

BLOB function result when ASCII-8BIT encoding

---

ext/sqlite3/database.c
test/test_database.rb

I seem that `close` method should be called even when given block rises an error.

Call close in ensure

---

lib/sqlite3/database.rb
test/test_integration.rb

Two issues are covered by this commit:
* We make use of the value of `result` to define the value of the
aggreator. Before that, `finalize` was used and this was not
respecting the documentation;
* Each call to `finalize` now resets the aggregator. In the future,
there could be some kind of callback/DSL to make it configurable.
Commit by:
* Richard K. Michael <rmichael@edgeofthenet.org>
* Franck Verrot <franck@verrot.fr>

Align #create_aggregate with #create_aggregate_handler

---

ext/sqlite3/database.c
test/test_database.rb

I do not know a lot about Ruby garbage collection internals and the use of RB_GC_GUARD, but certainly from what I've found, keeping VALUE on the stack prevents premature collection.
I can easily cause a segfault by creating a user-defined function that itself creates Ruby objects while doing its work. This fix seems to alleviate the segfaults, and I think it's because this directly puts the VALUE pointers on the stack, where garbage collection cannot miss them.

Keep arg values on stack to prevent segfault in user-created function

---

lib/sqlite3/pragmas.rb

Some of the pragmas called in the Pragmas module were deprecated and new ones were missing.
So I updated the methods for pragma calls according to the currently supported pragmas listed on https://sqlite.org/pragma.html
This should fix #120

Updated the methods for pragma calls according to the currently

---

ext/sqlite3/sqlite3.c
test/test_database.rb
test/test_database_flags.rb
test/test_database_readonly.rb
test/test_database_readwrite.rb

This adds #ifdefs around the C constants for the sqlite3_open_v2 flags. I pulled tarballs from https://www.sqlite.org/src/taglist and built each sqlite3.h until I found the version where each constant first appears.

SQLITE_VERSION_NUMBER #ifdefs surrounding sqlite3_open_v2 constants

---

README.rdoc

I noticed that the example in the README.rdoc has a small issue: It doesn't _select_ the inserted rows from the second table.
I inserted an additional select statement into the example.

add missing SELECT into example in README.rdoc

---

ext/sqlite3/extconf.rb

This is slightly faster and doesn't rely on the format of `brew info`.

Use 'brew --prefix' for OS X/macOS compile flags

---

ext/sqlite3/database.c
ext/sqlite3/exception.c
lib/sqlite3/errors.rb
test/test_database.rb

Error code handling was previously completely broken, always returning nil. This fixes that and allows support for extended result codes, which provide more detail about what type of error has occurred (e.g. the specific type of constraint violated).

Fix error codes and support extended result codes

---

test/test_database.rb
test/test_statement.rb

- Use assert_nil if expecting nil, this will fail in MT6.
- Avoid deprecation warnings when testing.

Prepare for Minitest 6

---

ext/sqlite3/statement.c
test/test_statement.rb

#clear_bindings in `ext/sqlite3/statement.c` didn't have _bang at the end so I added it
`test_reset!` was also written in test_statement.rb, so I made `test_clear_bindings!` line up with that

fixed naming of bang method

---

CHANGELOG.rdoc
ext/sqlite3/database.c
lib/sqlite3/constants.rb
lib/sqlite3/database.rb
lib/sqlite3/version.rb

No breaking changes -- see commit msgs for details. The end game is to allow creating deterministic functions.

Add API for sending the "textrep" argument to sqlite3_create_function

---

lib/sqlite3/database.rb
test/test_integration.rb

If `@results_as_hash` is true, `row[0]` invokes `ResultSet::HashWithTypesAndFields.[](key)`. Given a numeric key this method will in turn call fields() which has been a deprecated API for 5 years.
The problem is that a library user with $VERBOSE=1 will receive a useless deprecation warning:
```
/Library/Ruby/Gems/2.0.0/gems/sqlite3-1.3.12/lib/sqlite3/resultset.rb:65
:in `[]' is calling SQLite3::ResultSet::HashWithTypesAndFields#fields.
This method will be removed in sqlite3 version 2.0.0, please call the
`columns` method on the SQLite3::ResultSet object that created this
object.
```
The library user cannot make sense of this message without reading the sqlite3-ruby source code. If the user reads the source code he will realize that there is nothing he can do about the warnings except for …

Avoid deprecated row[0] call in get_first_value() with @results_as_hash=true

---

ext/sqlite3/database.c

Super minor, and I know there's a pull request open for aggregator functions, but I thought I'd fix this typo in the meantime.

Fix typo in ext/database.c

---

Gemfile
rakelib/gem.rake
rakelib/native.rake

Update rake-compiler and rake-compiler-dock to support ruby-2.4 fat binary gems. This drops support for ruby-1.9.3 binary gems.
In the second commit this adds msys2 library dependency tag in gem metadata.
RubyInstaller2 supports metadata tags for installation of dependent MSYS2/MINGW libraries. The sqlite3 source gem requires the sqlite3 library to be installed on the system, which the gem installer takes
care about, when this tag is set.
The feature is documented here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency

Add ruby24 to fat binaries and add mingw dependency tag

---

Gemfile
rakelib/gem.rake
sqlite3.gemspec

A gemspec in git allows using a patched version of a gem in a project. Moreover a gemspec allows to install gems from git, when the fat binary gem is not yet available (see #228). Due to [a flaw in bundler](https://github.com/bundler/bundler/issues/5337) it's not easily possible to switch bundler to the corresponding source gem otherwise.
Install via gemspec is also what I recommend for RubyInstaller [in the FAQ](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#q-are-there-recommendations-for-working-with-rails).

Add a gemspec file via hoe-gemspec

---

.travis.yml
ext/sqlite3/extconf.rb

Link against `dl` and cat `mkmf.log` in case of failure.
Fixes #231

Try catting the mkmf.log file if there is a failure

---

ext/sqlite3/extconf.rb

Sqlite3-ruby doesn't use dl functions, nor does extconf compile sqlite3 sources, which possibly makes use of them. So mandating dl functions in extconf is wrong and breaks the build on Windows.
Fixes #250 .
This reverts commit f4ffec281a2888c1e536662ac1ea740fd3f5433c.

 Don't mandate dl functions for the extention build

---

.travis.yml
ext/sqlite3/database.c
ext/sqlite3/extconf.rb
ext/sqlite3/statement.c
test/test_integration_resultset.rb
test/test_statement.rb

This is a followup on @kamipo's #273 
It also avoid calling `rb_check_safe_obj` on MRI 2.7. That warning is totally spamming Active Record's test suite.
cc @tenderlove since apparently you're maintainer.
cc @rafaelfranca @Edouard-Chin.
NB: Based on @kamipo's PR I expect half of the CI jobs to fail, I'll try to make them pass by pushing another commit.

Remove deprecated taint followup

---

ext/sqlite3/database.c
ext/sqlite3/statement.c
test/test_integration_resultset.rb
test/test_statement.rb

The Ruby core team decided to deprecate the taint mechanism in Ruby 2.7
and will remove that in Ruby 3.
https://bugs.ruby-lang.org/issues/16131
https://github.com/ruby/ruby/pull/2476
In Ruby 2.7, `Object#{taint,untaint,trust,untrust}` and related
functions in the C-API no longer have an effect (all objects are always
considered untainted), and are now warned deprecation message.
https://buildkite.com/rails/rails/builds/65054#5aa2db21-569d-4202-99cd-a8323cab583e/6-8

The taint mechanism will be deprecated in Ruby 2.7

---

.github/workflows/windows.yml
rakelib/native.rake
rakelib/vendor_sqlite3.rake

1. Add rake compile:msys2 to allow compiling with MSYS2 sqlite3 package
2. Add .github/workflows/windows.yml to run GitHub Actions on Ruby 2.4 thru master on Windows

Add GitHub Actions for Windows CI

---

.travis.yml
Gemfile

This shows that CI is working for the current master.  The main fix is in .travis.yml.
The fix in the gemfile is due to hoe not having a `required_ruby_version` in its gemspec, as the last two releases are incompatible with Ruby 1.9.3 & 2.0. I believe it cannot be added to the code for `rake bundler:gemfile`, so it's a temp fix.
Opened an issue in hoe for it this morning.

Travis fix

---

ext/sqlite3/database.c

This isn't ideal but I couldn't figure out why the warning was thrown (and escalated as an error), so I just disabled it if using MSVC to fix #284

Allow building on MSVC by disabling a warning turned error.

---

lib/sqlite3/database.rb
test/test_database.rb

The argument is a file *path* but is called *file* and yet it's treated as a string.
If passed an actual File or a Pathname it will be properly handled.

Handle the file argument properly

---

ext/sqlite3/database.c
lib/sqlite3/database.rb
test/test_database.rb

Add a strict: true option.
Ref: https://github.com/rails/rails/pull/45101
Ref: https://github.com/rails/rails/issues/27782
Ref: https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted
Sqlite has a really unfortunate behavior around double quotes. It first tries to consider them as column names, but if they don't exist it then consider them as string literals.
Because of this, typos can silently go unnoticed. It would be very useful for Active Record if this behavior could be disabled.
cc @tenderlove @fatkodima

Add a `strict: true` option.

---

.github/workflows/sqlite3-ruby.yml

This PR does some minor enhancements for GitHub Actions workflows.
- Bump actions/checkout from v2 to v3
- Enable bundler-cache in MSP-Greg/setup-ruby-pkgs@v1

Update GitHub Actions workflows

---

CHANGELOG.rdoc
lib/sqlite3/version.rb

@tenderlove @larskanis can one of you please merge and cut a release if this is satisfactory? I don't have rubygems.org permissions.
@casperisfine has asked for a release to address https://github.com/rails/rails/pull/45101 (see https://github.com/sparklemotion/sqlite3-ruby/pull/317 for context).

version bump to v1.4.3

---

ext/sqlite3/extconf.rb

Since 1.5.0.rc1, two patch releases of sqlite3 have dropped.
https://www.sqlite.org/releaselog/3_39_2.html
This PR updates the packaged sqlite3 to v3.39.2.

dep: update packaged sqlite3 to v3.39.2

---

ext/sqlite3/extconf.rb

Any of the standard mkmf `dir_config` parameters for `sqlcipher` now imply both `--enable-system-libraries` and `--with-sqlcipher`. Specifically these are `--with-sqlicpher-dir`, `--with-sqlcipher-include`, and `--with-sqlcipher-lib`.
Also I've added a `--help` option that emits info about the supported parameters. That help text is:
```
USAGE: ruby #{$PROGRAM_NAME} [options]
Flags that are always valid:
--disable-system-libraries
Use the packaged libraries, and ignore the system libraries.
(This is the default behavior.)
--enable-system-libraries
Use system libraries instead of building and using the packaged libraries.
--with-sqlcipher
Use libsqlcipher instead of libsqlite3.
(Implies `--enable-system-libraries`.)
--help
Display this message.
Flags only used when using system libraries: …
```

ext: smarter sqlcipher config params, and a user help message

---

.github/workflows/sqlite3-ruby.yml
ext/sqlite3/extconf.rb
ext/sqlite3/sqlite3_ruby.h

Changing the vcpkg input from "sqlcipher" to "sqlite3 sqlcipher" seems to allow compile & test to pass?  Not.sure.
Also, ci log for 'bundle exec rake test' shows:
```
info: sqlite3-ruby version: 1.5.0.rc1/1.5.0.rc1
info: sqlite3 version: 3.39.1/3.37.2
info: sqlcipher?: true
info: threadsafe?: true
```
Not sure what 'sqlite3 version: 3.39.1/3.37.2' is about?
Lastly, CI is ran on Windows 'mingw', which is a Ruby head build, 'ucrt' is also available...  Didn't change.

Fixes for Windows mswin & sqlcipher 

---

.github/workflows/sqlite3-ruby.yml
test/test_sqlite3.rb

Similar to PR #333, adds a test to verify that compile & runtime sqlite3 versions are the same.
From watching Puma & EventMachine (both compile with OpenSSL), macOS has issues when using brew packages, the solution here is to use `--with-opt-dir=$(brew --prefix sqlite3)` when compiling.
Third comment can be removed, it just contains reformatting of the Actions yaml...
Failure with TruffleRuby-head, see PR #334 for info.  It is a recent failure.

test: assert compiled and loaded versions of sqlite3 are the same, update sqlite3-ruby.yml

---

ext/sqlite3/database.c

* TruffleRuby uses TruffleString which requires all UTF-16 strings to
always have an even bytesize.
* The code here ensures the UTF-16 string always ends up with 2 \x00
bytes, so append them explicitly to have an even bytesize instead of
relying on RSTRING_PTR() adding the second \x00 byte.
* Fixes https://github.com/oracle/truffleruby/issues/2704
This fixes the CI on TruffleRuby.

Fix utf16_string_value_ptr() for TruffleRuby

---

ext/sqlite3/extconf.rb

@Watson1978 pointed out in #335 that the 1.5.0.rc1 performance was worse than 1.4.4. At least part of the reason for this is that we didn't turn on compiler optimizations in 1.5.0.rc1.
This should improve the situation for both the precompiled native and the vanilla gems.

perf: use -O2 compiler optimizations

---

CHANGELOG.md
README.md
ext/sqlite3/extconf.rb

https://sqlite.org/releaselog/3_39_3.html

dep: update packaged sqlite3 to v3.39.3

---

ext/sqlite3/aggregator.c

* Otherwise the GC might read the variable when it is not pointing to a Ruby object yet.
* TruffleRuby also assumes it can read the pointer when
rb_gc_register_address() is called: https://github.com/oracle/truffleruby/issues/2720

rb_gc_register_address() must be called after the variable was assigned

---

CHANGELOG.md
ext/sqlite3/extconf.rb

https://sqlite.org/releaselog/3_39_4.html
From the release notification sent by sqlite maintainers:
> Version 3.39.4 is a minimal patch against the prior release that addresses issues found since the prior release.  In particular, a potential vulnerability in the FTS3 extension has been fixed, so this should be considered a security update.
>
> In order to exploit the vulnerability, an attacker must have full SQL access and must be able to construct a corrupt database with over 2GB of FTS3 content.  The problem arises from a 32-bit signed integer overflow.

dep: update packaged sqlite3 to v3.39.4

---

.github/workflows/gem-install.yml
bin/test-gem-file-contents
dependencies.yml
ext/sqlite3/extconf.rb
rakelib/native.rake
sqlite3.gemspec

fix: sqlite tarball packaging

---

.github/workflows/sqlite3-ruby.yml
ext/sqlite3/extconf.rb

This PR is two commits:
- first a CI job to reproduce the underlying failure
- then a commit to work around upstream https://github.com/flavorjones/mini_portile/issues/118
Closes #354

Work around Fedora pkgconf issue

---

.github/workflows/upstream.yml
ext/sqlite3/extconf.rb

Sqlite 3.34.0 is going to come out soon, and I'd like to be able to build against upstream edge.
This PR does two things:
- add a `--with-sqlite-source-dir=` option to extconf.rb
- add a new CI pipeline that uses that option to build against edge sqlite

ci: build against edge sqlite

---

lib/sqlite3/pragmas.rb
test/test_pragmas.rb

Fix `get_boolean_pragma` comparison:
- ### Problem
`get_boolean_pragma` always returns true because
the value returned from the db is an Int not a String.
cc/ @rafaelfranca @casperisfine

Fix `get_boolean_pragma` comparison:

---

ext/sqlite3/extconf.rb
ext/sqlite3/sqlite3.c

This works around new Darwin Ruby 3.2 symbol resolution issues, but also follows best practices around shipping shared libraries.
The result is that the only public (exported) symbol in the extension is `Init_sqlite3_native`, regardless of what platform or version of Ruby you're on.
See https://github.com/rake-compiler/rake-compiler-dock/issues/87 for lots of context.

ext: export only Init_sqlite3_native

---

.github/workflows/gem-install.yml
.github/workflows/sqlite3-ruby.yml
.github/workflows/upstream.yml
appveyor.yml
ext/sqlite3/backup.c
ext/sqlite3/database.c
ext/sqlite3/sqlite3.c
ext/sqlite3/statement.c

Three commits:
- avoid compiler warnings about old-style function definitions
- ensure pkg-config is installed on macos CI images (to fix the build)
- run the full test suite weekly

ci: fix the build and run it weekly to prevent bitrot

---

CHANGELOG.md
CONTRIBUTING.md
dependencies.yml

https://sqlite.org/releaselog/3_41_0.html
From the release announcement:
> This is a routine maintenance release.  Upgrading is optional.

dep: update packaged sqlite3 to 3.41.0

---

.github/workflows/sqlite3-ruby.yml
Gemfile
rakelib/test.rake
sqlite3.gemspec
test/test_database.rb
test/test_deprecated.rb
test/test_encoding.rb
test/test_result_set.rb
test/test_statement.rb
test/test_statement_execute.rb

- use `ruby_memcheck` to invoke valgrind on the test suite to look for leaks and memory errors
- add the valgrind test to CI
- clean up the tests to properly close Database, Statement, and ResultSet objects

Add a valgrind test task, and clean up resource management in the tests

---

dependencies.yml
test/test_integration_statement.rb

https://sqlite.org/releaselog/3_43_0.html
From the upstream changelog:
> SQLite Release 3.43.0 On 2023-08-24
> * Add support for Contentless-Delete FTS5 Indexes. This is a variety of FTS5 full-text search index that omits storing the content that is being indexed while also allowing records to be deleted.
> * Enhancements to the date and time functions:
>   * Added new time shift modifiers of the form ±YYYY-MM-DD HH:MM:SS.SSS.
>   * Added the timediff() SQL function.
> * Added the octet_length(X) SQL function.
> * Added the sqlite3_stmt_explain() API.
> * Query planner enhancements:
>   * Generalize the LEFT JOIN strength reduction optimization so that it works for RIGHT and FULL JOINs as well. Rename it to OUTER JOIN strength reduction.
>   * Enhance the theorem prover in the OUTER JOIN …

dep: update sqlite3 to v3.43.0

---

INSTALLATION.md
ext/sqlite3/extconf.rb

feat: allow setting sqlite compiler flags via extconf args

---

.github/dependabot.yml
.github/workflows/sqlite3-ruby.yml
CONTRIBUTING.md
Gemfile
bin/build-gems
ext/sqlite3/database.c
ext/sqlite3/statement.c
lib/sqlite3/database.rb
lib/sqlite3/resultset.rb
lib/sqlite3/translator.rb
lib/sqlite3/version.rb
rakelib/test.rake
sqlite3.gemspec
test/test_database.rb
test/test_integration_resultset.rb
test/test_statement.rb

- address int-to-long compiler warnings on darwin/clang
- improve documented release steps
- drop ruby_memcheck binary name setting
- update gemspec authors, summary, and description
- pin dev dependencies, and turn on dependabot updates

some general cleanup

---

dependencies.yml
test/test_database.rb

From the changelog at See https://sqlite.org/releaselog/3_43_1.html :
> - Fix a regression in the way that the [sum()](https://sqlite.org/lang_aggfunc.html#sumunc), [avg()](https://sqlite.org/lang_aggfunc.html#avg), and [total()](https://sqlite.org/lang_aggfunc.html#sumunc) aggregate functions handle infinities.
> - Fix a bug in the [json_array_length()](https://sqlite.org/json1.html#jarraylen) function that occurs when the argument comes directly from [json_remove()](https://sqlite.org/json1.html#jrm).
> - Fix the omit-unused-subquery-columns optimization (introduced in in version 3.42.0) so that it works correctly if the subquery is a compound where one arm is DISTINCT and the other is not.
> - Other minor fixes.
Closes #396

dep: update packaged sqlite to 3.43.1

---

CHANGELOG.md
ext/sqlite3/extconf.rb

See https://fractaledmind.github.io/2023/09/10/enhancing-rails-sqlite-optimizing-compilation/
Would love feedback @fractaledmind @hopsoft

ext: compile sqlite with WAL_SYNCHRONOUS=1 and --enable-fts5

---

dependencies.yml

From the forum announcement:
> SQLite version 3.43.2 is now available.  Version 3.43.2 is a small patch
to version 3.43.1 and 3.43.0 that fixes some minor inaccuracies and also
addresses some problems in the build scripts.  The changes probably do not
affect your projects, but you are welcomed to upgrade nevertheless.
Details from https://sqlite.org/releaselog/3_43_2.html
> - Fix a couple of obscure UAF errors and an obscure memory leak.
> - Omit the use of the sprintf() function from the standard library in the [CLI](https://sqlite.org/cli.html), as this now generates warnings on some platforms.
> - Avoid conversion of a double into unsigned long long integer, as some platforms do not do such conversions correctly.

dep: update packaged sqlite3 to 3.43.2

---

Gemfile

Psych was only added in #363 because psych 5 wouldn't build on some CI platforms, but that seems to be fixed now.

dep: remove psych as an explicit dep

---

lib/sqlite3/database.rb
test/test_database.rb

To make it follow common pattern, like for File:
result = File.open('/dev/zero') do |f|
f.read(10)
end
See discussion in https://github.com/sparklemotion/sqlite3-ruby/discussions/414

make SQLite3::Database.open return the block result instead of the db instance

---

.github/workflows/gem-install.yml
.github/workflows/sqlite3-ruby.yml
.github/workflows/upstream.yml

The issue described at https://github.com/oracle/truffleruby/issues/3328 highlighted that we're testing edge rubies in the primary CI pipeline, causing noisy false negative signals.
Let's adopt the same practice as Nokogiri, and test edge rubies in an "upstream" pipeline, and test only stable rubies in the primary CI pipelines.

ci: test edge rubies only in upstream.yml

---

.github/workflows/gem-install.yml
CHANGELOG.md
bin/test-gem-file-contents
rakelib/native.rake
sqlite3.gemspec

- drop support completely for Ruby `1.9.2 .. 2.6` (inclusive)
- drop native gem support for 2.7 (but keep general support for 2.7)
I'd really like feedback on dropping so many old versions. The honest truth is that we haven't tested anything older than 2.7 for the last year, anyway.

dep: drop support for old rubies

---

.github/workflows/gem-install.yml

because 3.19 fails due to #434. While I work on better musl support, this makes CI a bit more meaningful.

ci: pin alpine to 3.18

---

.github/workflows/gem-install.yml
.github/workflows/sqlite3-ruby.yml
.github/workflows/upstream.yml

Note that this won't go green until there are official docker images for ruby:3.3 and there's a windows build available from rubyinstaller2 for setup-ruby to use.

ci: update pipelines to test with ruby 3.3.0 final

---

ext/sqlite3/statement.c
lib/sqlite3/statement.rb

Move statement#initialize to Ruby so that we don't need to use C apis to set instance variables

Move Statement#initialize to Ruby

---

ext/sqlite3/database.c
lib/sqlite3/database.rb

We don't need to define this in C

Move the encoding method to Ruby

---

.editorconfig
ext/sqlite3/aggregator.c
ext/sqlite3/aggregator.h
ext/sqlite3/backup.c
ext/sqlite3/backup.h
ext/sqlite3/database.c
ext/sqlite3/database.h
ext/sqlite3/exception.c
ext/sqlite3/exception.h
ext/sqlite3/sqlite3.c
ext/sqlite3/statement.c
ext/sqlite3/statement.h
rakelib/format.rake

and some other conventions that we're using in Nokogiri.

style(c): adopt cruby conventions

---

lib/sqlite3/database.rb
test/test_integration_pending.rb

One of the largest pain-points when using SQLite in a Rails app is the limited concurrency support. While SQLite does support only one writer, from a Rails app's point-of-view this does not mean that that app simply cannot run in, for example, Puma clustered mode. As I have [detailed](https://fractaledmind.github.io/2023/12/11/sqlite-on-rails-improving-concurrency/), the primary issues are that the GVL isn't released while the SQLite `busy_timeout` C function is running and transactions are run in `DEFERRED` mode. 
We can solve the first of these by providing a Ruby `busy_handler` callback that will release the GVL between retries. This allows multiple threads to naturally coordinate and "queue up" to acquire SQLite's single write lock.
I initially proposed providing this in the Rails …

Add a busy_handler_timeout setter

---

ext/sqlite3/statement.c
sqlite3.gemspec
test/test_resource_cleanup.rb

Prevents memory leak in the case that `close` is not called before a `ResultSet` is garbage collected.
`close` sets `c->st` to `NULL` immediately after calling `sqlite3_finalize` itself, so there is no double-free risk introduced with this change.

Always call sqlite3_finalize in deallocate func

---

lib/sqlite3/database.rb
test/test_integration_pending.rb

After chatting with @fractaledmind and @tenderlove I've reverting this until we understand the CI flakiness and get get a repeatable green.
This PR is the outcome of running:
git revert f80c5ff0..0c93d308

Revert pull request #443 from fractaledmind/lock-wait-timeout

---

ext/sqlite3/database.c
ext/sqlite3/database.h

Previous discussion in https://github.com/sparklemotion/sqlite3-ruby/pull/458
Storing `VALUE self` as context for `rb_sqlite3_busy_handler` is unsafe because as of Ruby 2.7, the GC compactor may move objects around which can lead to this reference pointing to either another random object or to garbage.
Instead we can store the callback reference inside the malloced struct (`sqlite3Ruby`) which can't possibly move, and then inside the handler, get the callback reference from that struct.
This however requires to define a mark function for the database object, and while I was at it, I implemented compaction support for it so we don't pin that proc.
cc @flavorjones @tenderlove

Fix a GC compaction issue with `busy_handler`

---

lib/sqlite3/database.rb
lib/sqlite3/resultset.rb
lib/sqlite3/statement.rb
test/test_integration_resultset.rb

"Results as hash" should be set on the database, so we should only need to check it once when we first start the query.  This patch pulls result set construction in to a factory method on the database object.  Doing this eliminates a "translate to hash" check that is performed on every row fetch.

Use a factory method to eliminate "results as hash" check

---

lib/sqlite3/database.rb
test/test_integration_pending.rb

Since https://github.com/sparklemotion/sqlite3-ruby/pull/443 required a revert (https://github.com/sparklemotion/sqlite3-ruby/pull/457) because the test for `busy_timeout` holding the GVL such that other working threads could not progress was flaky (particularly on `windows-latest, packaged` CI builds), this PR re-introduces the `busy_handler_timeout` but with only one resilient test that the `busy_handler_timeout` definitely does allow other working threads to progress. The negative test of `busy_timeout` is unnecessary in addition to being flaky.

busy_handler_timeout pt2

---

CHANGELOG.md
lib/sqlite3/database.rb
lib/sqlite3/resultset.rb
test/test_integration_pending.rb
test/test_statement.rb

This commit removes deprecated row array wrappers.  If you want to access "types" for a particular query, then use a prepared statement.
Deprecated / removed code looks like this:
```ruby
row = @db.execute("select * from foo")
assert_equal ["blob"], row.first.types
```
If you would like to access the "types" associated with a returned query, use a prepared statement like this:
```ruby
@db.prepare("select * from foo") do |v|
assert_equal ["blob"], v.types
end
```

Remove row array wrappers

---

ext/sqlite3/statement.c
lib/sqlite3/statement.rb
test/test_statement.rb

Resolves https://github.com/sparklemotion/sqlite3-ruby/issues/410
This PR adds 9 instance methods to the `Statement` class:
* `fullscan_steps`
* `sorts`
* `autoindexes`
* `vm_steps`
* `reprepares`
* `runs`
* `filter_misses`
* `filter_hits`
* `memused`
Each method corresponds to one of the [counters](https://www.sqlite.org/c3ref/c_stmtstatus_counter.html) available to the [`stmt_status`](https://www.sqlite.org/c3ref/stmt_status.html) interface. 
I wasn't sure how best to name the methods. There were two paths I considered: either mapping from the counter constant names or trying to find the clearest, most semantic name for the value. I decided to go with path one as this should make searching for methods from SQLite reference easier. We could add method aliases if we want to add more …

Implement sqlite3_stmt_status interface

---

lib/sqlite3/database.rb
test/test_encoding.rb

This is a regression test for Rails. Rails instantiates SQLite3 with `results_as_hash` set to `true` by default. I broke the encoding method when that value is set to true, so this patch fixes it.

Ensure the `Database#encoding` method works when results are "as hash"

---

ext/sqlite3/statement.c
lib/sqlite3/database.rb
test/test_encoding.rb
test/test_statement.rb

Freeze strings and row records so that we can more easily share results among Ractors
Silly example, but here's an example of using database results plus Ractors to make a parallel producer-consumer pattern:
```ruby
require "sqlite3"
require "securerandom"
def fib n
if n < 2
n
else
fib(n-2) + fib(n-1)
end
end
N = 10
queue = Ractor.new do
while (work = Ractor.receive)
Ractor.yield work
end
N.times { Ractor.yield nil }
end
workers = N.times.map do
Ractor.new(queue) do |q|
while (work = q.take)
name, i = work
p "Ractor: #{Ractor.current} #{name}: #{fib(i)}"
end
end
end
db = SQLite3::Database.new ":memory:"
db.execute 'CREATE TABLE "fibs" (name string, fib int)'
stmt = db.prepare "INSERT INTO fibs (name, fib) VALUES (?, ?)"
5000.times { stmt.execute SecureRandom.hex, rand(30) }
stmt.close …
```

Freeze results that come from the database

---

.github/workflows/ci.yml
Gemfile
test/helper.rb

This is some overdue cleanup of our CI pipeline.

ci: refactor workflow

---

CHANGELOG.md
Gemfile
dependencies.yml

https://www.sqlite.org/releaselog/3_45_0.html

dep: update vendored sqlite to 3.45.0 (1-7-stable)

---

dependencies.yml

https://www.sqlite.org/releaselog/3_45_0.html
Note that CHANGELOG entry will be forward-ported later from the 1.7.x release branch.

dep: update vendored sqlite to 3.45.0 (main)

---

lib/sqlite3/database.rb
test/test_encoding.rb

Database encoding can be changed, and we don't want to intercept all queries just to check if someone changed the encoding. This commit removes the encoding cache. If applications find that they are querying the database encoding frequently, they should cache the return value of this method themselves

Don't cache the database encoding

---

ext/sqlite3/database.c
test/test_database.rb

Fix encoding for values passed to custom functions

---

ext/sqlite3/extconf.rb
ext/sqlite3/statement.c
test/test_statement.rb

When we get column names back from the database, it's very common to always return the same strings. This patch uses Ruby's "interned string" API so that we're always getting the same string objects back from the database.
Fixes: #155

Intern column names so we always get the same string

---

CHANGELOG.md
ext/sqlite3/aggregator.c
ext/sqlite3/database.c
ext/sqlite3/exception.c
ext/sqlite3/exception.h
lib/sqlite3/pragmas.rb
test/test_database.rb
test/test_pragmas.rb

use SQLite3::Exception classes consistently
- Pragmas methods were raising StandardError
- Database#execute_batch2 was raising RuntimeError
- Database#load_extension was raising RuntimeError
- the fallback for unknown errors was RuntimeError
Fixes #302

use `SQLite3::Exception` consistently

---

CHANGELOG.md
dependencies.yml

https://www.sqlite.org/releaselog/3_45_1.html

dep: update vendored sqlite to 3.45.1 (1-7-stable)

---

CHANGELOG.md
dependencies.yml

https://www.sqlite.org/releaselog/3_45_1.html
(cherry-picked from e9bfbdbe on 1-7-stable)

dep: update vendored sqlite to 3.45.1 (main)

---

ext/sqlite3/statement.c
test/test_statement.rb

These methods allow you to retrieve the SQL statement that was used to create the statement object.  The `sql` method just returns the sql statement, where the `expanded_sql` method returns the statement but with bind parameters substituted.
This should aid with debugging and other tasks.
Fixes #293

Add `sql` and `expanded_sql` methods to the statement object

---

README.md
lib/sqlite3/database.rb

Add threadsafety documentation

---

ext/sqlite3/exception.c
ext/sqlite3/exception.h
ext/sqlite3/statement.c

cc @tenderlove 
This actually was caught by the test suite in https://github.com/sparklemotion/sqlite3-ruby/actions/runs/7745352446/job/21121203412#step:6:82 but I missed it because we've been having some flaky failures of the valgrind/memcheck suite (see https://github.com/sparklemotion/sqlite3-ruby/issues/489).

fix: expanded sql leak

---

CHANGELOG.md
lib/sqlite3/database.rb
test/test_database.rb

Database#transaction returns block result

---

lib/sqlite3/database.rb

This code depends on a SQLite API which is deprecated, `sqlite3_aggregate_count` ([docs](https://www.sqlite.org/c3ref/aggregate_count.html)). In addition, the present implementation is broken (`@driver` is always nil). Related: #164.
[This check](https://github.com/sparklemotion/sqlite3-ruby/actions/runs/8106559146/job/22156728792?pr=509) failed and appears unrelated to this code change.

Remove FunctionProxy#count

---

lib/sqlite3/database.rb

The `FunctionProxy` class has contained this broken method, which doesn't work because `@driver` is not set, since aaa74ebd.
See related #509 which removed `#count`.
Fixes #164.

fix: remove `FunctionProxy#set_error`

---

lib/sqlite3/database.rb
test/test_database.rb

This is part of what's requested in https://github.com/sparklemotion/sqlite3-ruby/issues/243. (The other part is to take an array of statements, but that is not implemented here.)

execute_batch returns result of last statement

---

CHANGELOG.md
dependencies.yml

https://sqlite.org/releaselog/3_45_2.html

dep: update sqlite to 3.45.2 (1-7-stable branch)

---

dependencies.yml

From the forum announcement:
> This is a patch release with minimal changes.  None of the problems fixed are critical so updating is not an emergency.  See the change log or the "news" page for details.
See also:
- https://sqlite.org/releaselog/3_45_3.html
- https://sqlite.org/src/timeline?from=version-3.45.2&to=version-3.45.3

dep: update sqlite3 to 3.45.3 from 3.45.2

---

.github/workflows/ci.yml
Gemfile
bin/test-gem-install
rakelib/native.rake

This is a draft PR that will remain open while we work on a general fix for musl version issues.
Fixes #434
Fixes #372

introduce general musl support

---

CHANGELOG.md
ext/sqlite3/sqlite3.c
lib/sqlite3/constants.rb
test/test_sqlite3.rb

This function is useful for understanding the runtime performance of sqlite.
This is a very thin layer on top of the sqlite3 library's function, so it allows full usage of it from Ruby.
I've tested with `./bin/build-gems` and it built fine and the tests passed.

Add SQLite3.status to call sqlite3_status

---

CHANGELOG.md
lib/sqlite3/database.rb
test/test_statement.rb

Make sure Database#execute, #query, and #execute_batch raise an ArgumentError to avoid silent problems.
This should have been done in ae129046
Related to #525
A potential alternative is to revert ae129046

fix: raise an exception if multiple bind parameters aren't an array

---

CHANGELOG.md
ext/sqlite3/statement.c
test/test_database.rb

Fix a regression in v2.0.0 that caused `Database#execute_batch` to raise an encoding exception when passed some non-ASCII strings. As a result of this fix, `Database#prepare` now ensures the "remainder" string will always be encoded as UTF-8.
Closes #524

fix: Database#execute_batch properly handles non-ASCII strings

---

.github/workflows/ci.yml

See related flavorjones/ruby-c-extensions-explained#30

ci: test native installation on arm64-darwin

---

rakelib/test.rake
test/test_integration_pending.rb

Following the pattern from #459 let's speed the GVL tests up

test: improve the "busy handler timeout" GVL test

---

CHANGELOG.md
dependencies.yml

https://sqlite.org/releaselog/3_46_0.html

dep: update vendored sqlite3 to 3.46.0

---

lib/sqlite3/database.rb

Every call allocate two static strings.
```
$ ruby --yjit /tmp/sqlite3.rb
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) +YJIT [arm64-darwin23]
Warming up --------------------------------------
sqlite3 quote   870.178k i/100ms
gsub fstr     1.090M i/100ms
Calculating -------------------------------------
sqlite3 quote      9.058M (±11.9%) i/s -     44.379M in   5.058563s
gsub fstr     11.955M (± 9.1%) i/s -     59.939M in   5.083400s
Comparison:
sqlite3 quote:  9058148.2 i/s
gsub fstr: 11955119.6 i/s - 1.32x  faster
```
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
gem "benchmark-ips"
end
require 'benchmark/ips'
eval <<~RUBY
def sqlite3_quote(str)
str.gsub("'", "''")
end
RUBY
def …
```

SQLite3::Database#quote: avoid allocating useless strings

---

.github/workflows/upstream.yml

This seems to be a new requirement as of around 2024-08-06, see https://sqlite.org/forum/forumpost/45c4862d37 and other forum posts for more context.
Example failure: https://github.com/sparklemotion/sqlite3-ruby/actions/runs/10280777092/job/28462644002

ci: ensure tcl-dev is installed to build upstream sqlite from source

---

ext/sqlite3/database.c
lib/sqlite3/database.rb

The Database type struct is marked as `WB_PROTECTED` which means that any new references added to the object need to fire the write barrier. Previously we were missing this when setting the `busy_handler`.
I wasn't able to make a smaller reproduction, but I started investigating this after seeing this crash in the Rails CI suite: https://buildkite.com/rails/rails/builds/111147#0191d7ec-de81-49c8-b20a-d207f446d45e
```
<OBJ_INFO:gc_mark_ptr@gc.c:7072> 0x00007f4fd042cb20 [0 M    ] T_NONE
test/cases/connection_pool_test.rb:1041: [BUG] try to mark T_NONE object
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
-- Control frame information -----------------------------------------------
c:0060 p:---- s:0311 e:000310 CFUNC  :initialize
c:0059 p:---- s:0308 e:000307 CFUNC  :new
c:0058 …
```

Use write barrier when setting busy_handler

---

CHANGELOG.md
ext/sqlite3/database.c
test/test_database.rb

Close databases in a deferred manner if there are unclosed prepared statements. Previously closing a database while statements were open resulted in a `BusyException`.
See https://www.sqlite.org/c3ref/close.html for more context.

Use sqlite3_close_v2 to close databases.

---

.github/workflows/ci.yml
.rubocop.yml
CHANGELOG.md
INSTALLATION.md
bin/test-gem-file-contents
rakelib/native.rake
sqlite3.gemspec
test/test_discarding.rb

Primarily because it doesn't support Process._fork, but also because it's been EOL for many months.
Note that this also drops the x64-mingw32 native gem, because RubyInstaller builds with UCRT starting with Ruby 3.1.

Drop support for Ruby 3.0

---

ext/sqlite3/database.c
ext/sqlite3/database.h
ext/sqlite3/statement.c
ext/sqlite3/statement.h
test/test_discarding.rb
test/test_statement.rb

Closes #564 which pointed out a performance regression from #558.
This also restores the ability (now tested!) to call `Database#close` successfully and defer its cleanup until after `Statement`s are closed, which was the promise of #557 and `sqlite3_close_v2`.
Running the benchmark @tenderlove wrote for #564:
```ruby
#!/usr/bin/env ruby
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "sqlite3", path: "."
gem "benchmark-ips"
end
require "sqlite3"
require "benchmark/ips"
file = "/tmp/test.sqlite3"
begin
File.unlink file
rescue
nil
end
db = SQLite3::Database.new file
db.execute "create table foo (id int)"
1000.times do |i|
db.execute "insert into foo (id) values (#{i})"
end
Benchmark.ips do |x|
x.report("selecting") {
db.execute("select * from foo").to_a
}
end
db.close …
```

Optimize the statement check for a non-discarded database

---

CHANGELOG.md
ext/sqlite3/exception.c
ext/sqlite3/exception.h
ext/sqlite3/extconf.rb
ext/sqlite3/statement.c
lib/sqlite3/errors.rb
test/test_integration.rb

for errors that occur when preparing a SQL statement
@flavorjones @tenderlove @byroot 
This is a proof-of-concept PR to explore providing better context for exceptions raised. To begin, I focused on exceptions raised when attempting to prepare a statement. Using the gem over the years, there are other contexts that I found the error messages lacking, but I need to recall them and work on PoCs for each. But I wanted to open this to start the conversation around improving error messages with context.

Provide the SQL statement context 

---

ext/sqlite3/extconf.rb

Note that these changes are backwards-compatible with 3.47.x.
See https://sqlite.org/src/info/32fc9c3f62601684

ext: update configure options for upcoming 3.48.x.

---

CHANGELOG.md
ext/sqlite3/extconf.rb
test/helper.rb
test/test_database_uri.rb

See https://www.sqlite.org/uri.html

feat: allow URI filenames

---

CHANGELOG.md
lib/sqlite3/constants.rb
lib/sqlite3/pragmas.rb
test/test_pragmas.rb

The SQLite docs recommend some cases where `PRAGMA optimize;` should be used: https://www.sqlite.org/pragma.html#pragma_optimize
I have discovered recently a case where this helped a project at work (https://twitter.com/alexcwatt/status/1851094243323912631) and now I'm wondering about how to make this easier to discover and use.
Do we want a way to test that these wrappers translate to the expected `execute` call? I wasn't sure what tests to write for this change.

Add convenience wrapper for pragma optimize

---

CHANGELOG.md
lib/sqlite3/pragmas.rb
test/test_pragmas.rb

Found an incorrect setting in the database encoding pragma that could potentially cause character encoding issues.
```ruby
irb(main):012> a = SQLite3::Database.new(":memoery:")
=>
#<SQLite3::Database:0x000000011f6b5330
...
irb(main):013> a.encoding = "utf-16be "
/app/vendor/bundle/ruby/3.3.0/gems/sqlite3-2.2.0-arm64-darwin/lib/sqlite3/statement.rb:36:in `prepare': unsupported encoding: UTF-16BE : (SQLite3::SQLException)
PRAGMA encoding='UTF-16BE '
from /app/vendor/bundle/ruby/3.3.0/gems/sqlite3-2.2.0-arm64-darwin/lib/sqlite3/statement.rb:36:in `initialize'
from /app/vendor/bundle/ruby/3.3.0/gems/sqlite3-2.2.0-arm64-darwin/lib/sqlite3/database.rb:170:in `new'
from /app/vendor/bundle/ruby/3.3.0/gems/sqlite3-2.2.0-arm64-darwin/lib/sqlite3/database.rb:170:in `prepare'
from …
```

Fix invalid encoding name

---

.rdoc_options
ext/sqlite3/extconf.rb
ext/sqlite3/sqlite3.c
lib/sqlite3.rb
lib/sqlite3/version.rb
lib/sqlite3/version_info.rb
rakelib/check-manifest.rake
sqlite3.gemspec
test/helper.rb

New constants track additional metadata:
- `SQLite3::SQLITE_PACKAGED_LIBRARIES` (boolean) true if the gem is using the packaged libsqlite3, false if system libraries
- `SQLite3::SQLITE_PRECOMPILED_LIBRARIES` (boolean) true if the gem is using precompiled packaged libsqlite3
New constant tracking a potpourri of metadata: `SQLite3::VERSION_INFO`
This should unblock #578

Track metadata in VERSION_INFO

---

CHANGELOG.md
ext/sqlite3/extconf.rb
test/test_database.rb

Hi. Similar to https://github.com/TryGhost/node-sqlite3/issues/1279 . This PR enables `dbstat` table, that contains useful info like size of tables, indexes, etc. useful for debugging.

Enable dbstat table by default

---

CHANGELOG.md
ext/sqlite3/extconf.rb

doc: remove mention of the pkg-config gem from extconf warning

---

.github/workflows/ci.yml

which may not be necessary anymore? It's slow on the aarch64-linux systems so let's try to remove it.

ci: remove gem-update-system

---

.rdoc_options
ext/sqlite3/database.c
lib/sqlite3/database.rb
lib/sqlite3/version.rb
test/test_database.rb

Using [sqlite extensions](https://www.sqlite.org/loadext.html) in a Rails app is currently a bit tricky.
Assuming you can figure out how to compile it, where do you put the extension on disk? If it's provided by a gem, how do you get a reliable path that works robustly across environments and upgrades?
Do you monkeypatch the sqlite3 adapter to call `#load_extension`, or do you explicitly inject the extension yourself before any query that needs it?
Using sqlite extensions shouldn't be this hard.
The goal of this PR is to enable injection of sqlite extensions by specifying the name of a Ruby constant in a Rails database config:
```yaml
development:
adapter: sqlite3
database: storage/development.sqlite3
extensions:
- SQLean::Crypto
```
Over this past weekend, I packaged up the …

feat: easier and more flexible loading of sqlite extensions

---

lib/sqlite3/fork_safety.rb

If GC runs between the check for `db.weakref_alive?` and `db.close` then an exception will be raised:
Invalid Reference - probably recycled (WeakRef::RefError)
I personally saw this error when running a Rails app test suite in parallel, so while it's rare it does happen.
In this case, let's just swallow the error and keep going, since the database object isn't in use and was GCed.

fix: handle the case where GC runs during fork safety checks

---

test/test_database_uri.rb

See discussion at #612 where it's revealed that Fedora does not enable this feature in its system library.

test: skip database URI tests when using system libraries

---

.github/workflows/ci.yml
.github/workflows/downstream.yml
Gemfile
bin/test-gem-build
bin/test-gem-install
rakelib/format.rake

Move dependencies related to style and documentation into a separate 'development' group in the Gemfile, and exclude that group from CI wherever possible.
Also remove libyaml-dev from the list of things we install on test containers, because hopefully we don't need it anymore.

dep: move style and docs deps into a separate group

---

CHANGELOG.md
dependencies.yml
ext/sqlite3/database.c
ext/sqlite3/extconf.rb
test/test_database.rb

This skips 3.48.0 and 3.49.0 because the autoconf package is not building properly across all platforms, as noted in comments below.
- https://sqlite.org/releaselog/3_48_0.html
- https://sqlite.org/releaselog/3_49_0.html
- https://sqlite.org/releaselog/3_49_1.html
Note that this PR also updates tests to not expect to be able to load extensions when running on Windows systems using the packaged library. The autoconf amalgamation is not picking up dlopen during configuration on Windows systems and I have been unable to figure out why.

dep: update vendored sqlite to 3.49.1

---

lib/sqlite3/pragmas.rb

I'm looking in earnest at Ractor support in Rails. We need some of these constants that SQLite3 uses to be frozen so that when they're accessed via Ractors we don't get an error.
This commit just adds frozen string literals, and freezes some constants

Freeze strings and constants in pragmas

---

lib/sqlite3/database.rb
lib/sqlite3/pragmas.rb
test/test_pragmas.rb

This PR is just trying to simplify pragma related constants.  I guess these constants are used as a kind of lookup table.  I added some regression tests because I saw we're not exercising all cases in the test suite, then refactored the constants to just be hash tables.
I left the very strange array search in `set_enum_pragma` for backwards compatibility, though I think we should deprecate it.
AFAICT, there are two types of pragmas. One uses integers, the other strings.  I think if we changed some of the pragma APIs, we could delete the hash tables that are simply duplicated strings, but I'll do that in a follow up PR.

Try to simplify pragma related constants

---

.github/workflows/upstream.yml

It's been failing for the past few weeks with linker errors like:
```
/usr/bin/ld: tclsqlite-shell.o: in function `DbProfileHandler':
tclsqlite.c:(.text+0x458): undefined reference to `sqlite3_snprintf'
/usr/bin/ld: tclsqlite-shell.o: in function `tclSqlFunc':
tclsqlite.c:(.text+0x60c): undefined reference to `sqlite3_user_data'
/usr/bin/ld: tclsqlite.c:(.text+0x6f2): undefined reference to `sqlite3_result_text64'
/usr/bin/ld: tclsqlite.c:(.text+0x75e): undefined reference to `sqlite3_value_double'
/usr/bin/ld: tclsqlite.c:(.text+0x78e): undefined reference to `sqlite3_value_type'
/usr/bin/ld: tclsqlite.c:(.text+0x7f9): undefined reference to `sqlite3_result_error'
/usr/bin/ld: tclsqlite.c:(.text+0x824): undefined reference to `sqlite3_value_bytes'
/usr/bin/ld: tclsqlite.c:(.text+0x830): …
```

ci: get upstream sqlite-head job green

---

CHANGELOG.md
dependencies.yml

https://sqlite.org/releaselog/3_50_1.html
From the announcement:
> upgrading is recommended due to the JSON fix described by item 12 on the change log
Item 12 is:
> Fix a long-standing bug in [jsonb_set()](https://sqlite.org/json1.html#jsetb) and similar that was exposed by new optimizations added in version 3.50.0.

dep: update vendored sqlite to 3.50.1

---

.github/workflows/ci.yml
ext/sqlite3/extconf.rb
patches/001-dl-and-pthread-flags.patch

Apply the upstream fix from https://github.com/sqlite/sqlite/commit/d9eae6b75a37e63c30c3c05c5c1fc7ed425589cd
Fixes https://github.com/sparklemotion/sqlite3-ruby/issues/634

Ensure we can resolve dlopen et al
