README.rdoc
Fixed comment that describes creating a table
=> Added table creation that is necessary to run example in synopsis

.travis.yml
=> output mkmf.log so we can see the errors

Gemfile, tasks/gem.rake
=> Update rake-compiler-dock to support RubyInstaller-2.3.0

README.rdoc
It's not that big of a deal, but it was really BUGGING me
No pun intended
It's not a bug
Waffles
=> readme fix

faq/faq.md
Not sure if you actually want this (another thing to maintain?) but it helped me out.  Pull it if you want it.
=> Added a FAQ in Markdown

test/test_statement.rb
This test was empty, so I wrote it in.
It's a little different from the other `bind_param` tests and the cost is a little higher, but I think the intention/end result is a little more clear
Thanks
=> test_statement.rb: add bind blob test

.travis.yml
Hello!
Is it possible to add Ruby 2.4 to Travis CI?
Thanks.
=> Add Ruby 2.4.1 to Travis CI

.travis.yml
This PR clears out one unused setting, which no longer does things.
(The #251 is the PR which fixes the build, this one only removes a nit.)
=> Travis: Drop unused setting "sudo: false"

Rakefile
=> Fix typo on post install message by sqlite3-ruby(dummy gem)

CHANGELOG.rdoc, lib/sqlite3/version.rb
Let's please ship a new version to fix an issue (#324) introduced in v1.4.3.
=> version bump to v1.4.4

.github/workflows/gem-install.yml
companion commit to 60679c8, see #336 for related work.
=> ci: gem-install.yml uses --with-opt-dir for macos system libraries

CHANGELOG.md, ext/sqlite3/database.c, test/test_database.rb
and raise TypeError if it's not a String
Fixes #339
=> fix: Database#load_extension check argument type

.github/workflows/gem-install.yml
Trying to reproduce https://github.com/oracle/truffleruby/issues/2729
=> ci: install gem under truffleruby

.github/workflows/sqlite3-ruby.yml, CHANGELOG.md, dependencies.yml
Update packaged sqlite3 to v3.40.0
https://sqlite.org/releaselog/3_40_0.html
=> dep: update packaged sqlite3 to v3.40.0

sqlite3.gemspec
include test file added by #275
=> gem: fix manifest

CHANGELOG.md, dependencies.yml
https://sqlite.org/releaselog/3_40_1.html
Closes #366
=> dep: update packaged sqlite3 to v3.40.1

.github/workflows/gem-install.yml, .github/workflows/sqlite3-ruby.yml, CHANGELOG.md, bin/test-gem-file-contents, ext/sqlite3/extconf.rb, rakelib/native.rake
=> native gem support: add 3.2, drop 2.6

CHANGELOG.md, dependencies.yml
https://sqlite.org/releaselog/3_42_0.html
=> dep: update sqlite3 to v3.42.0

dependencies.yml
See https://sqlite.org/forum/forumpost/2b631bb2f8
=> update sqlite checksums, which apparently changed

dependencies.yml
https://sqlite.org/releaselog/3_44_0.html
=> dep: update sqlite to 3.44.0

lib/sqlite3/resultset.rb
=> Don't flatten row array before passing to Hash#[]

test/test_database.rb
=> test: update tests to accommodate changed error messages

dependencies.yml
https://sqlite.org/releaselog/3_45_2.html
=> dep: update vendored sqlite to v3.45.2

.github/workflows/ci.yml
Add basic FreeBSD coverage to CI
=> ci: add freebsd coverage

dependencies.yml
https://sqlite.org/releaselog/3_46_1.html
=> dep: update vendored sqlite to v3.46.1

dependencies.yml
https://sqlite.org/releaselog/3_47_0.html
=> dep: bump sqlite to v3.47.0

dependencies.yml
https://sqlite.org/releaselog/3_47_1.html
=> dep: update vendored sqlite to 3.47.1

dependencies.yml
https://sqlite.org/releaselog/3_47_2.html
=> dep: bump vendored sqlite to v3.47.2

Gemfile, rakelib/native.rake
and bump the ruby versions in native.rake
See https://github.com/rake-compiler/rake-compiler-dock/releases/tag/v1.8.0
=> dep: update rake-compiler-dock to v1.8.0

dependencies.yml
https://sqlite.org/releaselog/3_50_2.html
=> dep: update vendored SQLite to 3.50.2

dependencies.yml
https://www.sqlite.org/releaselog/3_50_4.html
=> dep: update vendored sqlite3 to v3.50.4
